# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/mainTitleBar.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(669, 541)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dropShadowLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.dropShadowLayout.setContentsMargins(10, 10, 10, 10)
        self.dropShadowLayout.setSpacing(0)
        self.dropShadowLayout.setObjectName("dropShadowLayout")
        self.dropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        self.dropShadowFrame.setStyleSheet("background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.4375 rgba(25, 25, 25, 255), stop:1 rgba(81, 81, 81, 255));\n"
"border-radius: 10px;")
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dropShadowFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleBar = QtWidgets.QFrame(self.dropShadowFrame)
        self.titleBar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.titleBar.setStyleSheet("background: none;")
        self.titleBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titleBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleBar.setObjectName("titleBar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.titleBar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.title = QtWidgets.QFrame(self.titleBar)
        self.title.setStyleSheet("background: none;")
        self.title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title.setObjectName("title")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.title)
        self.horizontalLayout_2.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.title)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setMaximumSize(QtCore.QSize(20, 20))
        self.label_3.setStyleSheet("background: none;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("UI\\../DJCSAppLogo2.png"))
        self.label_3.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(82, 30))
        font = QtGui.QFont()
        font.setFamily("Blackadder ITC")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgba(255,255,255); padding: 3px;")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgba(235,0,0);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_2.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.title)
        self.buttons = QtWidgets.QFrame(self.titleBar)
        self.buttons.setMaximumSize(QtCore.QSize(100, 50))
        self.buttons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons.setObjectName("buttons")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.buttons)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.maximize = QtWidgets.QPushButton(self.buttons)
        self.maximize.setMinimumSize(QtCore.QSize(15, 15))
        self.maximize.setMaximumSize(QtCore.QSize(15, 15))
        self.maximize.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.295455 rgba(85, 255, 40, 255), stop:0.778409 rgba(81, 81, 81, 255));\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-radius: 10px;\n"
"    background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.119318 rgba(81, 81, 81, 255), stop:0.744318 rgba(85, 255, 40, 255));\n"
"}")
        self.maximize.setText("")
        self.maximize.setObjectName("maximize")
        self.horizontalLayout_4.addWidget(self.maximize)
        self.minimize = QtWidgets.QPushButton(self.buttons)
        self.minimize.setMinimumSize(QtCore.QSize(15, 15))
        self.minimize.setMaximumSize(QtCore.QSize(15, 15))
        self.minimize.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 20px;\n"
"border-style: outset;\n"
"border-radius: 10px;\n"
"    background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.267045 rgba(255, 255, 0, 255), stop:0.8125 rgba(81, 81, 81, 255));\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.0340909 rgba(81, 81, 81, 255), stop:0.664773 rgba(255, 255, 0, 255));\n"
"}")
        self.minimize.setText("")
        self.minimize.setIconSize(QtCore.QSize(15, 15))
        self.minimize.setShortcut("")
        self.minimize.setFlat(False)
        self.minimize.setObjectName("minimize")
        self.horizontalLayout_4.addWidget(self.minimize)
        self.close = QtWidgets.QPushButton(self.buttons)
        self.close.setMinimumSize(QtCore.QSize(15, 15))
        self.close.setMaximumSize(QtCore.QSize(15, 15))
        self.close.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.272727 rgba(255, 40, 40, 255), stop:0.801136 rgba(81, 81, 81, 255));\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    border-radius: 10px;\n"
"    background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.119318 rgba(81, 81, 81, 255), stop:0.744318 rgba(255, 40, 40, 255));\n"
"}")
        self.close.setText("")
        self.close.setObjectName("close")
        self.horizontalLayout_4.addWidget(self.close)
        self.horizontalLayout.addWidget(self.buttons)
        self.verticalLayout.addWidget(self.titleBar)
        self.content = QtWidgets.QFrame(self.dropShadowFrame)
        self.content.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.content.setStyleSheet("background: none;")
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.gridLayout = QtWidgets.QGridLayout(self.content)
        self.gridLayout.setObjectName("gridLayout")
        self.initialSetup = QtWidgets.QPushButton(self.content)
        self.initialSetup.setMinimumSize(QtCore.QSize(150, 50))
        self.initialSetup.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.initialSetup.setFont(font)
        self.initialSetup.setTabletTracking(False)
        self.initialSetup.setStyleSheet("QPushButton{\n"
"background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.0852273 rgba(25, 25, 25, 255), stop:0.335227 rgba(207, 207, 207, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
"color: rgba(235, 0, 0, 255);\n"
"border: 0;\n"
"}\n"
"QPushButton:Hover{\n"
"color: rgba(25,25,25);\n"
"    background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.113636 rgba(255, 40, 40, 255), stop:0.352273 rgba(207, 207, 207, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
"}")
        self.initialSetup.setObjectName("initialSetup")
        self.gridLayout.addWidget(self.initialSetup, 2, 2, 1, 1)
        self.site3 = QtWidgets.QPushButton(self.content)
        self.site3.setMinimumSize(QtCore.QSize(50, 50))
        self.site3.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.site3.setFont(font)
        self.site3.setStyleSheet("QPushButton{\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
"color: rgb(235, 235, 235);\n"
"border: 0;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
"}")
        self.site3.setObjectName("site3")
        self.gridLayout.addWidget(self.site3, 3, 3, 1, 1)
        self.site5 = QtWidgets.QPushButton(self.content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.site5.sizePolicy().hasHeightForWidth())
        self.site5.setSizePolicy(sizePolicy)
        self.site5.setMinimumSize(QtCore.QSize(150, 50))
        self.site5.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.site5.setFont(font)
        self.site5.setStyleSheet("QPushButton{\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
"color: rgb(235, 235, 235);\n"
"border: 0;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
"}")
        self.site5.setObjectName("site5")
        self.gridLayout.addWidget(self.site5, 4, 2, 1, 1)
        self.site6 = QtWidgets.QPushButton(self.content)
        self.site6.setMinimumSize(QtCore.QSize(50, 50))
        self.site6.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.site6.setFont(font)
        self.site6.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.site6.setStyleSheet("QPushButton{\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
"color: rgb(235, 235, 235);\n"
"border: 0;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
"}")
        self.site6.setObjectName("site6")
        self.gridLayout.addWidget(self.site6, 4, 3, 1, 1)
        self.site8 = QtWidgets.QPushButton(self.content)
        self.site8.setMinimumSize(QtCore.QSize(50, 50))
        self.site8.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.site8.setFont(font)
        self.site8.setStyleSheet("QPushButton{\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
"color: rgb(235, 235, 235);\n"
"border: 0;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
"}")
        self.site8.setObjectName("site8")
        self.gridLayout.addWidget(self.site8, 5, 2, 1, 1)
        self.site9 = QtWidgets.QPushButton(self.content)
        self.site9.setMinimumSize(QtCore.QSize(50, 50))
        self.site9.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.site9.setFont(font)
        self.site9.setStyleSheet("QPushButton{\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
"color: rgb(235, 235, 235);\n"
"border: 0;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
"}")
        self.site9.setObjectName("site9")
        self.gridLayout.addWidget(self.site9, 5, 3, 1, 1)
        self.site7 = QtWidgets.QPushButton(self.content)
        self.site7.setMinimumSize(QtCore.QSize(50, 50))
        self.site7.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.site7.setFont(font)
        self.site7.setStyleSheet("QPushButton{\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
"color: rgb(235, 235, 235);\n"
"border: 0;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
"}")
        self.site7.setObjectName("site7")
        self.gridLayout.addWidget(self.site7, 5, 1, 1, 1)
        self.site4 = QtWidgets.QPushButton(self.content)
        self.site4.setMinimumSize(QtCore.QSize(50, 50))
        self.site4.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.site4.setFont(font)
        self.site4.setStyleSheet("QPushButton{\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
"color: rgb(235, 235, 235);\n"
"border: 0;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
"}")
        self.site4.setObjectName("site4")
        self.gridLayout.addWidget(self.site4, 4, 1, 1, 1)
        self.amarillo = QtWidgets.QPushButton(self.content)
        self.amarillo.setMinimumSize(QtCore.QSize(150, 50))
        self.amarillo.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.amarillo.setFont(font)
        self.amarillo.setStyleSheet("QPushButton{\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
"color: rgb(235, 235, 235);\n"
"border: 0;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
"}")
        self.amarillo.setObjectName("amarillo")
        self.gridLayout.addWidget(self.amarillo, 3, 2, 1, 1)
        self.wichitaFalls = QtWidgets.QPushButton(self.content)
        self.wichitaFalls.setMinimumSize(QtCore.QSize(50, 50))
        self.wichitaFalls.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.wichitaFalls.setFont(font)
        self.wichitaFalls.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.wichitaFalls.setStyleSheet("QPushButton{\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
"color: rgb(235, 235, 235);\n"
"border: 0;\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
"}")
        self.wichitaFalls.setAutoDefault(False)
        self.wichitaFalls.setDefault(True)
        self.wichitaFalls.setFlat(False)
        self.wichitaFalls.setObjectName("wichitaFalls")
        self.gridLayout.addWidget(self.wichitaFalls, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.content)
        self.credits = QtWidgets.QFrame(self.dropShadowFrame)
        self.credits.setMaximumSize(QtCore.QSize(16777215, 30))
        self.credits.setStyleSheet("background: none;")
        self.credits.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.credits.setFrameShadow(QtWidgets.QFrame.Raised)
        self.credits.setObjectName("credits")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.credits)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.credits_2 = QtWidgets.QFrame(self.credits)
        self.credits_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.credits_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.credits_2.setObjectName("credits_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.credits_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.credits_2)
        self.label_4.setStyleSheet("QLabel{\n"
"color: rgba(0,0,0,0);\n"
"}\n"
"\n"
"QLabel:Hover{\n"
"color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0.25 rgba(182, 55, 255, 255), stop:0.505682 rgba(0, 255, 0, 255), stop:0.75 rgba(182, 55, 255, 255));\n"
"}")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.frame_2 = QtWidgets.QFrame(self.credits_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6.addWidget(self.frame_2)
        self.horizontalLayout_5.addWidget(self.credits_2)
        self.grip = QtWidgets.QFrame(self.credits)
        self.grip.setMaximumSize(QtCore.QSize(30, 30))
        self.grip.setStyleSheet("padding: 5px;")
        self.grip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.grip.setObjectName("grip")
        self.horizontalLayout_5.addWidget(self.grip)
        self.verticalLayout.addWidget(self.credits)
        self.dropShadowLayout.addWidget(self.dropShadowFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Tocarro\'s"))
        self.label_2.setText(_translate("MainWindow", "Automation App"))
        self.initialSetup.setText(_translate("MainWindow", "Initial Setup"))
        self.site3.setText(_translate("MainWindow", "Site 3"))
        self.site5.setText(_translate("MainWindow", "Site 5"))
        self.site6.setText(_translate("MainWindow", "Site 6"))
        self.site8.setText(_translate("MainWindow", "Site 8"))
        self.site9.setText(_translate("MainWindow", "Site 9"))
        self.site7.setText(_translate("MainWindow", "Site 7"))
        self.site4.setText(_translate("MainWindow", "Site 4"))
        self.amarillo.setText(_translate("MainWindow", "Amarillo"))
        self.wichitaFalls.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>WF</p></body></html>"))
        self.wichitaFalls.setText(_translate("MainWindow", "Wichita Falls"))
        self.label_4.setText(_translate("MainWindow", "Designed and Programmed by: Kenneth Schaefer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
