# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(648, 511)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dropShadowLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.dropShadowLayout.setContentsMargins(10, 10, 10, 10)
        self.dropShadowLayout.setSpacing(0)
        self.dropShadowLayout.setObjectName("dropShadowLayout")
        self.drop_shadow_frame = QtWidgets.QFrame(self.centralwidget)
        self.drop_shadow_frame.setStyleSheet(
            "background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.4375 rgba(25, 25, 25, 255), stop:1 rgba(81, 81, 81, 255));border-radius: 10px;")
        self.drop_shadow_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.drop_shadow_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.drop_shadow_frame.setObjectName("drop_shadow_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.drop_shadow_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.title_bar.setMaximumSize(QtCore.QSize(1900, 50))
        self.title_bar.setStyleSheet("background: transparent;")
        self.title_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_title = QtWidgets.QFrame(self.title_bar)
        self.frame_title.setStyleSheet("background: transparent;")
        self.frame_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_title)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_title)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_btns = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.frame_btns.sizePolicy().hasHeightForWidth())
        self.frame_btns.setSizePolicy(sizePolicy)
        self.frame_btns.setMaximumSize(QtCore.QSize(70, 30))
        self.frame_btns.setToolTipDuration(100)
        self.frame_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setLineWidth(0)
        self.frame_btns.setObjectName("frame_btns")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_btns)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_close = QtWidgets.QPushButton(self.frame_btns)
        self.btn_close.setMinimumSize(QtCore.QSize(15, 15))
        self.btn_close.setMaximumSize(QtCore.QSize(15, 15))
        self.btn_close.setToolTipDuration(1)
        self.btn_close.setStyleSheet("QPushButton {\n"
                                     "    color: #333;\n"
                                     "    border: 2px solid #555;\n"
                                     "    border-radius: 7px;\n"
                                     "    border-style: outset;\n"
                                     "    background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.272727 rgba(255, 40, 40, 255), stop:0.801136 rgba(81, 81, 81, 255));\n"
                                     "}\n"
                                     "\n"
                                     "\n"
                                     "QPushButton:hover {\n"
                                     "    border-radius: 7px;\n"
                                     "    background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.119318 rgba(81, 81, 81, 255), stop:0.744318 rgba(255, 40, 40, 255));\n"
                                     "}")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_4.addWidget(self.btn_close)
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_minimize.setMinimumSize(QtCore.QSize(15, 15))
        self.btn_minimize.setMaximumSize(QtCore.QSize(15, 15))
        self.btn_minimize.setMouseTracking(False)
        self.btn_minimize.setTabletTracking(False)
        self.btn_minimize.setAcceptDrops(False)
        self.btn_minimize.setToolTipDuration(100)
        self.btn_minimize.setStyleSheet("QPushButton {\n"
                                        "color: #333;\n"
                                        "border: 2px solid #555;\n"
                                        "    border-radius: 7px;\n"
                                        "border-style: outset;\n"
                                        "    background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.267045 rgba(255, 255, 0, 255), stop:0.8125 rgba(81, 81, 81, 255));\n"
                                        "\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "    border-radius: 7px;\n"
                                        "    background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.0340909 rgba(81, 81, 81, 255), stop:0.664773 rgba(255, 255, 0, 255));\n"
                                        "}")
        self.btn_minimize.setText("")
        self.btn_minimize.setIconSize(QtCore.QSize(15, 15))
        self.btn_minimize.setShortcut("")
        self.btn_minimize.setFlat(False)
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_4.addWidget(self.btn_minimize)
        self.btn_maximize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_maximize.setMinimumSize(QtCore.QSize(15, 15))
        self.btn_maximize.setMaximumSize(QtCore.QSize(15, 15))
        self.btn_maximize.setToolTipDuration(100)
        self.btn_maximize.setStyleSheet("QPushButton {\n"
                                        "    color: #333;\n"
                                        "    border: 2px solid #555;\n"
                                        "    border-radius: 7px;\n"
                                        "    border-style: outset;\n"
                                        "    background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.295455 rgba(85, 255, 40, 255), stop:0.778409 rgba(81, 81, 81, 255));\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "    border-radius: 7px;\n"
                                        "    background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.119318 rgba(81, 81, 81, 255), stop:0.744318 rgba(85, 255, 40, 255));\n"
                                        "}")
        self.btn_maximize.setText("")
        self.btn_maximize.setObjectName("btn_maximize")
        self.horizontalLayout_4.addWidget(self.btn_maximize)
        self.horizontalLayout_3.addWidget(self.frame_btns)
        self.label_title = QtWidgets.QLabel(self.frame)
        self.label_title.setMaximumSize(QtCore.QSize(167000, 35))
        font = QtGui.QFont()
        font.setFamily("Blackadder ITC")
        font.setPointSize(16)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet(
            "color: rgba(255,255,255,255); padding: 3px; background: transparent;")
        self.label_title.setTextFormat(QtCore.Qt.AutoText)
        self.label_title.setAlignment(
            QtCore.Qt.AlignBottom | QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_3.addWidget(self.label_title)
        self.label_title2 = QtWidgets.QLabel(self.frame)
        self.label_title2.setMaximumSize(QtCore.QSize(175, 30))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_title2.setFont(font)
        self.label_title2.setStyleSheet(
            "color:rgba(235,0,0); background: transparent;")
        self.label_title2.setAlignment(
            QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.label_title2.setObjectName("label_title2")
        self.horizontalLayout_3.addWidget(self.label_title2)
        self.logo = QtWidgets.QLabel(self.frame)
        self.logo.setMaximumSize(QtCore.QSize(40, 40))
        self.logo.setStyleSheet("")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("DJCSAppLogo.png"))
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.horizontalLayout_3.addWidget(self.logo)
        self.horizontalLayout_2.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.frame_title)
        self.verticalLayout.addWidget(self.title_bar)
        self.content_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.content_bar.setMaximumSize(QtCore.QSize(1900, 900))
        self.content_bar.setToolTip("")
        self.content_bar.setStyleSheet("QPushButton{\n"
                                       "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
                                       "color: rgb(235, 235, 235);\n"
                                       "border: 0;\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:Hover{\n"
                                       "background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
                                       "}")
        self.content_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_bar.setLineWidth(0)
        self.content_bar.setObjectName("content_bar")
        self.gridLayout = QtWidgets.QGridLayout(self.content_bar)
        self.gridLayout.setObjectName("gridLayout")
        self.amarillo = QtWidgets.QPushButton(self.content_bar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.amarillo.sizePolicy().hasHeightForWidth())
        self.amarillo.setSizePolicy(sizePolicy)
        self.amarillo.setMinimumSize(QtCore.QSize(100, 100))
        self.amarillo.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.amarillo.setFont(font)
        self.amarillo.setStyleSheet("QPushButton{\n"
                                    "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
                                    "color: rgb(235, 235, 235);\n"
                                    "border: 0;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:Hover{\n"
                                    "color: rgba(25,25,25,1);\n"
                                    "background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
                                    "}")
        self.amarillo.setObjectName("amarillo")
        self.gridLayout.addWidget(self.amarillo, 3, 2, 1, 1)
        self.ennis = QtWidgets.QPushButton(self.content_bar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.ennis.sizePolicy().hasHeightForWidth())
        self.ennis.setSizePolicy(sizePolicy)
        self.ennis.setMinimumSize(QtCore.QSize(100, 100))
        self.ennis.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ennis.setFont(font)
        self.ennis.setStyleSheet("QPushButton{\n"
                                 "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
                                 "color: rgb(235, 235, 235);\n"
                                 "border: 0;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:Hover{\n"
                                 "color: rgba(25,25,25,1);\n"
                                 "background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
                                 "}")
        self.ennis.setObjectName("ennis")
        self.gridLayout.addWidget(self.ennis, 4, 5, 1, 1)
        self.gresham = QtWidgets.QPushButton(self.content_bar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.gresham.sizePolicy().hasHeightForWidth())
        self.gresham.setSizePolicy(sizePolicy)
        self.gresham.setMinimumSize(QtCore.QSize(100, 100))
        self.gresham.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gresham.setFont(font)
        self.gresham.setObjectName("gresham")
        self.gridLayout.addWidget(self.gresham, 4, 6, 1, 1)
        self.gresham2 = QtWidgets.QPushButton(self.content_bar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.gresham2.sizePolicy().hasHeightForWidth())
        self.gresham2.setSizePolicy(sizePolicy)
        self.gresham2.setMinimumSize(QtCore.QSize(100, 100))
        self.gresham2.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gresham2.setFont(font)
        self.gresham2.setStyleSheet("QPushButton{\n"
                                    "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
                                    "color: rgb(235, 235, 235);\n"
                                    "border: 0;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:Hover{\n"
                                    "color: rgba(25,25,25,1);\n"
                                    "background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
                                    "}")
        self.gresham2.setObjectName("gresham2")
        self.gridLayout.addWidget(self.gresham2, 5, 1, 1, 1)
        self.hobbs = QtWidgets.QPushButton(self.content_bar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.hobbs.sizePolicy().hasHeightForWidth())
        self.hobbs.setSizePolicy(sizePolicy)
        self.hobbs.setMinimumSize(QtCore.QSize(100, 100))
        self.hobbs.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.hobbs.setFont(font)
        self.hobbs.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.hobbs.setStyleSheet("QPushButton{\n"
                                 "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
                                 "color: rgb(235, 235, 235);\n"
                                 "border: 0;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:Hover{\n"
                                 "color: rgba(25,25,25,1);\n"
                                 "background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
                                 "}")
        self.hobbs.setObjectName("hobbs")
        self.gridLayout.addWidget(self.hobbs, 5, 2, 1, 1)
        self.kaufman = QtWidgets.QPushButton(self.content_bar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.kaufman.sizePolicy().hasHeightForWidth())
        self.kaufman.setSizePolicy(sizePolicy)
        self.kaufman.setMinimumSize(QtCore.QSize(100, 100))
        self.kaufman.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.kaufman.setFont(font)
        self.kaufman.setStyleSheet("QPushButton{\n"
                                   "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
                                   "color: rgb(235, 235, 235);\n"
                                   "border: 0;\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton:Hover{\n"
                                   "color: rgba(25,25,25,1);\n"
                                   "background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
                                   "}")
        self.kaufman.setObjectName("kaufman")
        self.gridLayout.addWidget(self.kaufman, 5, 4, 1, 1)
        self.kaufman2 = QtWidgets.QPushButton(self.content_bar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.kaufman2.sizePolicy().hasHeightForWidth())
        self.kaufman2.setSizePolicy(sizePolicy)
        self.kaufman2.setMinimumSize(QtCore.QSize(100, 100))
        self.kaufman2.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.kaufman2.setFont(font)
        self.kaufman2.setStyleSheet("QPushButton{\n"
                                    "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
                                    "color: rgb(235, 235, 235);\n"
                                    "border: 0;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:Hover{\n"
                                    "color: rgba(25,25,25,1);\n"
                                    "background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
                                    "}")
        self.kaufman2.setObjectName("kaufman2")
        self.gridLayout.addWidget(self.kaufman2, 5, 5, 1, 1)
        self.krum = QtWidgets.QPushButton(self.content_bar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.krum.sizePolicy().hasHeightForWidth())
        self.krum.setSizePolicy(sizePolicy)
        self.krum.setMinimumSize(QtCore.QSize(100, 100))
        self.krum.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.krum.setFont(font)
        self.krum.setObjectName("krum")
        self.gridLayout.addWidget(self.krum, 5, 6, 1, 1)
        self.laughlin = QtWidgets.QPushButton(self.content_bar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.laughlin.sizePolicy().hasHeightForWidth())
        self.laughlin.setSizePolicy(sizePolicy)
        self.laughlin.setMinimumSize(QtCore.QSize(100, 100))
        self.laughlin.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.laughlin.setFont(font)
        self.laughlin.setObjectName("laughlin")
        self.gridLayout.addWidget(self.laughlin, 6, 1, 1, 1)
        self.lindale = QtWidgets.QPushButton(self.content_bar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.lindale.sizePolicy().hasHeightForWidth())
        self.lindale.setSizePolicy(sizePolicy)
        self.lindale.setMinimumSize(QtCore.QSize(100, 100))
        self.lindale.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lindale.setFont(font)
        self.lindale.setStyleSheet("QPushButton{\n"
                                   "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
                                   "color: rgb(235, 235, 235);\n"
                                   "border: 0;\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton:Hover{\n"
                                   "color: rgba(25,25,25,1);\n"
                                   "background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
                                   "}")
        self.lindale.setObjectName("lindale")
        self.gridLayout.addWidget(self.lindale, 6, 2, 1, 1)
        self.lubbock = QtWidgets.QPushButton(self.content_bar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.lubbock.sizePolicy().hasHeightForWidth())
        self.lubbock.setSizePolicy(sizePolicy)
        self.lubbock.setMinimumSize(QtCore.QSize(100, 100))
        self.lubbock.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lubbock.setFont(font)
        self.lubbock.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.lubbock.setStyleSheet("QPushButton{\n"
                                   "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
                                   "color: rgb(235, 235, 235);\n"
                                   "border: 0;\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton:Hover{\n"
                                   "color: rgba(25,25,25,1);\n"
                                   "background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
                                   "}")
        self.lubbock.setAutoDefault(False)
        self.lubbock.setDefault(True)
        self.lubbock.setFlat(False)
        self.lubbock.setObjectName("lubbock")
        self.gridLayout.addWidget(self.lubbock, 6, 4, 1, 1)
        self.mineola = QtWidgets.QPushButton(self.content_bar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.mineola.sizePolicy().hasHeightForWidth())
        self.mineola.setSizePolicy(sizePolicy)
        self.mineola.setMinimumSize(QtCore.QSize(100, 100))
        self.mineola.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mineola.setFont(font)
        self.mineola.setObjectName("mineola")
        self.gridLayout.addWidget(self.mineola, 6, 5, 1, 1)
        self.mineola2 = QtWidgets.QPushButton(self.content_bar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.mineola2.sizePolicy().hasHeightForWidth())
        self.mineola2.setSizePolicy(sizePolicy)
        self.mineola2.setMinimumSize(QtCore.QSize(100, 100))
        self.mineola2.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mineola2.setFont(font)
        self.mineola2.setObjectName("mineola2")
        self.gridLayout.addWidget(self.mineola2, 6, 6, 1, 1)
        self.paris = QtWidgets.QPushButton(self.content_bar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.paris.sizePolicy().hasHeightForWidth())
        self.paris.setSizePolicy(sizePolicy)
        self.paris.setMinimumSize(QtCore.QSize(100, 100))
        self.paris.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.paris.setFont(font)
        self.paris.setObjectName("paris")
        self.gridLayout.addWidget(self.paris, 7, 1, 1, 1)
        self.seminole = QtWidgets.QPushButton(self.content_bar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.seminole.sizePolicy().hasHeightForWidth())
        self.seminole.setSizePolicy(sizePolicy)
        self.seminole.setMinimumSize(QtCore.QSize(100, 100))
        self.seminole.setMaximumSize(QtCore.QSize(150, 150))
        self.seminole.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.seminole.setFont(font)
        self.seminole.setObjectName("seminole")
        self.gridLayout.addWidget(self.seminole, 7, 2, 1, 1)
        self.stillwater = QtWidgets.QPushButton(self.content_bar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.stillwater.sizePolicy().hasHeightForWidth())
        self.stillwater.setSizePolicy(sizePolicy)
        self.stillwater.setMinimumSize(QtCore.QSize(100, 100))
        self.stillwater.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.stillwater.setFont(font)
        self.stillwater.setObjectName("stillwater")
        self.gridLayout.addWidget(self.stillwater, 7, 4, 1, 1)
        self.tulsa = QtWidgets.QPushButton(self.content_bar)
        self.tulsa.setMinimumSize(QtCore.QSize(100, 100))
        self.tulsa.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.tulsa.setFont(font)
        self.tulsa.setTabletTracking(False)
        self.tulsa.setStyleSheet("QPushButton{\n"
                                 "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
                                 "color: rgb(235, 235, 235);\n"
                                 "border: 0;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:Hover{\n"
                                 "color: rgba(25,25,25,1);\n"
                                 "background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
                                 "}")
        self.tulsa.setObjectName("tulsa")
        self.gridLayout.addWidget(self.tulsa, 7, 5, 1, 1)
        self.wichita_falls = QtWidgets.QPushButton(self.content_bar)
        self.wichita_falls.setMinimumSize(QtCore.QSize(100, 100))
        self.wichita_falls.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.wichita_falls.setFont(font)
        self.wichita_falls.setStyleSheet("QPushButton{\n"
                                         "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
                                         "color: rgb(235, 235, 235);\n"
                                         "border: 0;\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:Hover{\n"
                                         "color: rgba(25,25,25,1);\n"
                                         "background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
                                         "}")
        self.wichita_falls.setObjectName("wichita_falls")
        self.gridLayout.addWidget(self.wichita_falls, 7, 6, 1, 1)
        self.enid = QtWidgets.QPushButton(self.content_bar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.enid.sizePolicy().hasHeightForWidth())
        self.enid.setSizePolicy(sizePolicy)
        self.enid.setMinimumSize(QtCore.QSize(100, 100))
        self.enid.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.enid.setFont(font)
        self.enid.setObjectName("enid")
        self.gridLayout.addWidget(self.enid, 4, 4, 1, 1)
        self.dallas = QtWidgets.QPushButton(self.content_bar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.dallas.sizePolicy().hasHeightForWidth())
        self.dallas.setSizePolicy(sizePolicy)
        self.dallas.setMinimumSize(QtCore.QSize(100, 100))
        self.dallas.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dallas.setFont(font)
        self.dallas.setObjectName("dallas")
        self.gridLayout.addWidget(self.dallas, 4, 2, 1, 1)
        self.caddo_mills = QtWidgets.QPushButton(self.content_bar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.caddo_mills.sizePolicy().hasHeightForWidth())
        self.caddo_mills.setSizePolicy(sizePolicy)
        self.caddo_mills.setMinimumSize(QtCore.QSize(100, 100))
        self.caddo_mills.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.caddo_mills.setFont(font)
        self.caddo_mills.setObjectName("caddo_mills")
        self.gridLayout.addWidget(self.caddo_mills, 4, 1, 1, 1)
        self.austin = QtWidgets.QPushButton(self.content_bar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.austin.sizePolicy().hasHeightForWidth())
        self.austin.setSizePolicy(sizePolicy)
        self.austin.setMinimumSize(QtCore.QSize(100, 100))
        self.austin.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.austin.setFont(font)
        self.austin.setStyleSheet("QPushButton{\n"
                                  "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
                                  "color: rgb(235, 235, 235);\n"
                                  "border: 0;\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:Hover{\n"
                                  "color: rgba(25,25,25,1);\n"
                                  "background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
                                  "}")
        self.austin.setObjectName("austin")
        self.gridLayout.addWidget(self.austin, 3, 5, 1, 1)
        self.verticalLayout.addWidget(self.content_bar)
        self.credits = QtWidgets.QFrame(self.drop_shadow_frame)
        self.credits.setMaximumSize(QtCore.QSize(1900, 30))
        self.credits.setStyleSheet("background: transparent;")
        self.credits.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.credits.setObjectName("credits")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.credits)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.credits_2 = QtWidgets.QFrame(self.credits)
        self.credits_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.credits_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.credits_2.setObjectName("credits_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.credits_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.credits_2)
        self.label_4.setStyleSheet("QLabel{\n"
                                   "color: rgba(0,0,0,0);\n"
                                   "}\n"
                                   "\n"
                                   "QLabel:Hover{\n"
                                   "color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0.25 rgba(182, 55, 255, 255), stop:0.505682 rgba(0, 255, 0, 255), stop:0.75 rgba(182, 55, 255, 255));\n"
                                   "}")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.frame_2 = QtWidgets.QFrame(self.credits_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6.addWidget(self.frame_2)
        self.horizontalLayout_5.addWidget(self.credits_2)
        self.frame_grip = QtWidgets.QFrame(self.credits)
        self.frame_grip.setMaximumSize(QtCore.QSize(30, 30))
        self.frame_grip.setStyleSheet("padding: 5px;")
        self.frame_grip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip.setObjectName("frame_grip")
        self.horizontalLayout_5.addWidget(self.frame_grip)
        self.verticalLayout.addWidget(self.credits)
        self.dropShadowLayout.addWidget(self.drop_shadow_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_close.setToolTip(_translate("MainWindow", "Close"))
        self.btn_minimize.setToolTip(_translate("MainWindow", "Minimize"))
        self.btn_maximize.setToolTip(_translate("MainWindow", "Maximize"))
        self.label_title.setText(_translate("MainWindow", "Tocarro\'s"))
        self.label_title2.setText(_translate("MainWindow", "Automation App"))
        self.amarillo.setText(_translate("MainWindow", "Amarillo"))
        self.ennis.setText(_translate("MainWindow", "Ennis"))
        self.gresham.setStyleSheet(_translate("MainWindow", "QPushButton{\n"
                                              "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
                                              "color: rgb(235, 235, 235);\n"
                                              "border: 0;\n"
                                              "}\n"
                                              "\n"
                                              "QPushButton:Hover{\n"
                                              "color: rgba(25,25,25,1);\n"
                                              "background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
                                              "}"))
        self.gresham.setText(_translate("MainWindow", "Gresham"))
        self.gresham2.setText(_translate("MainWindow", "Gresham 2"))
        self.hobbs.setText(_translate("MainWindow", "Hobbs"))
        self.kaufman.setText(_translate("MainWindow", "Kaufman"))
        self.kaufman2.setText(_translate("MainWindow", "Kaufman 2"))
        self.krum.setStyleSheet(_translate("MainWindow", "QPushButton{\n"
                                           "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
                                           "color: rgb(235, 235, 235);\n"
                                           "border: 0;\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:Hover{\n"
                                           "color: rgba(25,25,25,1);\n"
                                           "background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
                                           "}"))
        self.krum.setText(_translate("MainWindow", "Krum"))
        self.laughlin.setStyleSheet(_translate("MainWindow", "QPushButton{\n"
                                               "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
                                               "color: rgb(235, 235, 235);\n"
                                               "border: 0;\n"
                                               "}\n"
                                               "\n"
                                               "QPushButton:Hover{\n"
                                               "color: rgba(25,25,25,1);\n"
                                               "background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
                                               "}"))
        self.laughlin.setText(_translate("MainWindow", "Laughlin"))
        self.lindale.setText(_translate("MainWindow", "Lindale"))
        self.lubbock.setWhatsThis(_translate(
            "MainWindow", "<html><head/><body><p>WF</p></body></html>"))
        self.lubbock.setText(_translate("MainWindow", "Lubbock"))
        self.mineola.setStyleSheet(_translate("MainWindow", "QPushButton{\n"
                                              "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
                                              "color: rgb(235, 235, 235);\n"
                                              "border: 0;\n"
                                              "}\n"
                                              "\n"
                                              "QPushButton:Hover{\n"
                                              "color: rgba(25,25,25,1);\n"
                                              "background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
                                              "}"))
        self.mineola.setText(_translate("MainWindow", "Mineola"))
        self.mineola2.setStyleSheet(_translate("MainWindow", "QPushButton{\n"
                                               "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
                                               "color: rgb(235, 235, 235);\n"
                                               "border: 0;\n"
                                               "}\n"
                                               "\n"
                                               "QPushButton:Hover{\n"
                                               "color: rgba(25,25,25,1);\n"
                                               "background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
                                               "}"))
        self.mineola2.setText(_translate("MainWindow", "Mineola 2"))
        self.paris.setStyleSheet(_translate("MainWindow", "QPushButton{\n"
                                            "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
                                            "color: rgb(235, 235, 235);\n"
                                            "border: 0;\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:Hover{\n"
                                            "color: rgba(25,25,25,1);\n"
                                            "background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
                                            "}"))
        self.paris.setText(_translate("MainWindow", "Paris"))
        self.seminole.setStyleSheet(_translate("MainWindow", "QPushButton{\n"
                                               "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
                                               "color: rgb(235, 235, 235);\n"
                                               "border: 0;\n"
                                               "}\n"
                                               "\n"
                                               "QPushButton:Hover{\n"
                                               "color: rgba(25,25,25,1);\n"
                                               "background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
                                               "}"))
        self.seminole.setText(_translate("MainWindow", "Seminole"))
        self.stillwater.setStyleSheet(_translate("MainWindow", "QPushButton{\n"
                                                 "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
                                                 "color: rgb(235, 235, 235);\n"
                                                 "border: 0;\n"
                                                 "}\n"
                                                 "\n"
                                                 "QPushButton:Hover{\n"
                                                 "color: rgba(25,25,25,1);\n"
                                                 "background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
                                                 "}"))
        self.stillwater.setText(_translate("MainWindow", "Stillwater"))
        self.tulsa.setText(_translate("MainWindow", "Tulsa"))
        self.wichita_falls.setText(_translate("MainWindow", "Wichita Falls"))
        self.enid.setStyleSheet(_translate("MainWindow", "QPushButton{\n"
                                           "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
                                           "color: rgb(235, 235, 235);\n"
                                           "border: 0;\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:Hover{\n"
                                           "color: rgba(25,25,25,1);\n"
                                           "background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
                                           "}"))
        self.enid.setText(_translate("MainWindow", "Enid"))
        self.dallas.setStyleSheet(_translate("MainWindow", "QPushButton{\n"
                                             "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
                                             "color: rgb(235, 235, 235);\n"
                                             "border: 0;\n"
                                             "}\n"
                                             "\n"
                                             "QPushButton:Hover{\n"
                                             "color: rgba(25,25,25,1);\n"
                                             "background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
                                             "}"))
        self.dallas.setText(_translate("MainWindow", "Dallas"))
        self.caddo_mills.setStyleSheet(_translate("MainWindow", "QPushButton{\n"
                                                  "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.494318, stop:0.35 rgba(235, 0, 0, 255), stop:1 rgba(0,0,0,0), stop:1 rgba(0,0,0,0));\\ncolor: rgb(235, 235, 235);\\nborder: 0;\n"
                                                  "color: rgb(235, 235, 235);\n"
                                                  "border: 0;\n"
                                                  "}\n"
                                                  "\n"
                                                  "QPushButton:Hover{\n"
                                                  "color: rgba(25,25,25,1);\n"
                                                  "background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.758, fx:0.5, fy:0.494, stop:0.107955 rgba(207, 207, 207, 255), stop:0.335227 rgba(255, 40, 40, 255), stop:0.636364 rgba(25, 25, 25, 0));\n"
                                                  "}"))
        self.caddo_mills.setText(_translate("MainWindow", "Caddo Mills"))
        self.austin.setText(_translate("MainWindow", "Austin"))
        self.label_4.setText(_translate(
            "MainWindow", "Designed and Programmed by: Kenneth Schaefer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
